using UnityEngine;
using UnityEditor;
public sealed class EditrGUIReference : EditorWindow
{
    #region Reference    
    private static readonly string[] mList =
    {
        "AboutWIndowLicenseLabel"                       ,
        "AC LeftArrow"                                  ,
        "AC RightArrow"                                 ,
        "AnimationCurveEditorBackground"                ,
        "AnimationEventBackground"                      ,
        "AnimationEventTooltip"                         ,
        "AnimationEventTooltipArrow"                    ,
        "AnimationKeyframeBackground"                   ,
        "AnimationRowEven"                              ,
        "AnimationRowOdd"                               ,
        "AnimationSelectionTextField"                   ,
        "AnimationTimelineTick"                         ,
        "AnimPropDropdown"                              ,
        "AppToolbar"                                    ,
        "AS TextArea"                                   ,
        "BoldLabel"                                     ,
        "BoldToggle"                                    ,
        "ButtonLeft"                                    ,
        "ButtonMid"                                     ,
        "ButtonRight"                                   ,
        "CN Box"                                        ,
        "CN CountBadge"                                 ,
        "CN EntryBackEven"                              ,
        "CN EntryBackOdd"                               ,
        "CN EntryError"                                 ,
        "CN EntryInfo"                                  ,
        "CN EntryWarn"                                  ,
        "CN Message"                                    ,
        "CN StatusError"                                ,
        "CN StatusInfo"                                 ,
        "CN StatusWarn"                                 ,
        "ColorField"                                    ,
        "ColorPicker2DThumb"                            ,
        "ColorPickerBackground"                         ,
        "ColorPickerBox"                                ,
        "ColorPickerHorizThumb"                         ,
        "ColorPickerVertThumb"                          ,
        "Command"                                       ,
        "CommandLeft"                                   ,
        "CommandMid"                                    ,
        "CommandRight"                                  ,
        "ControlLabel"                                  ,
        "CurveEditorLabelTickmarks"                     ,
        "debug_layout_box"                              ,
        "dockarea"                                      ,
        "dockareaOverlay"                               ,
        "dockareaStandalone"                            ,
        "dragtab"                                       ,
        "dragtabbright"                                 ,
        "dragtabdropwindow"                             ,
        "DropDown"                                      ,
        "DropDownButton"                                ,
        "ErrorLabel"                                    ,
        "ExposablePopupItem"                            ,
        "ExposablePopupMenu"                            ,
        "EyeDropperHorizontalLine"                      ,
        "EyeDropperPickedPixel"                         ,
        "EyeDropperVerticalLine"                        ,
        "flow background"                               ,
        "flow navbar back"                              ,
        "flow navbar button"                            ,
        "flow navbar separator"                         ,
        "flow node 0"                                   ,
        "flow node 0 on"                                ,
        "flow node 1"                                   ,
        "flow node 1 on"                                ,
        "flow node 2"                                   ,
        "flow node 2 on"                                ,
        "flow node 3"                                   ,
        "flow node 3 on"                                ,
        "flow node 4"                                   ,
        "flow node 4 on"                                ,
        "flow node 5"                                   ,
        "flow node 5 on"                                ,
        "flow node 6"                                   ,
        "flow node 6 on"                                ,
        "flow node hex 0"                               ,
        "flow node hex 0 on"                            ,
        "flow node hex 1"                               ,
        "flow node hex 1 on"                            ,
        "flow node hex 2"                               ,
        "flow node hex 2 on"                            ,
        "flow node hex 3"                               ,
        "flow node hex 3 on"                            ,
        "flow node hex 4"                               ,
        "flow node hex 4 on"                            ,
        "flow node hex 5"                               ,
        "flow node hex 5 on"                            ,
        "flow node hex 6"                               ,
        "flow node hex 6 on"                            ,
        "flow node titlebar"                            ,
        "flow overlay area left"                        ,
        "flow overlay area right"                       ,
        "flow overlay box"                              ,
        "flow overlay foldout"                          ,
        "flow overlay header lower left"                ,
        "flow overlay header lower right"               ,
        "flow overlay header upper left"                ,
        "flow overlay header upper right"               ,
        "flow shader in 0"                              ,
        "flow shader in 1"                              ,
        "flow shader in 2"                              ,
        "flow shader in 3"                              ,
        "flow shader in 4"                              ,
        "flow shader in 5"                              ,
        "flow shader node 0"                            ,
        "flow shader node 0 on"                         ,
        "flow shader out 0"                             ,
        "flow shader out 1"                             ,
        "flow shader out 2"                             ,
        "flow shader out 3"                             ,
        "flow shader out 4"                             ,
        "flow shader out 5"                             ,
        "flow target in"                                ,
        "flow triggerPin in"                            ,
        "flow triggerPin out"                           ,
        "flow var 0"                                    ,
        "flow var 0 on"                                 ,
        "flow var 1"                                    ,
        "flow var 1 on"                                 ,
        "flow var 2"                                    ,
        "flow var 2 on"                                 ,
        "flow var 3"                                    ,
        "flow var 3 on"                                 ,
        "flow var 4"                                    ,
        "flow var 4 on"                                 ,
        "flow var 5"                                    ,
        "flow var 5 on"                                 ,
        "flow var 6"                                    ,
        "flow var 6 on"                                 ,
        "flow varPin in"                                ,
        "flow varPin out"                               ,
        "flow varPin tooltip"                           ,
        "Foldout"                                       ,
        "FoldOutPreDrop"                                ,
        "GameViewBackground"                            ,
        "Grad Down Swatch"                              ,
        "Grad Down Swatch Overlay"                      ,
        "Grad Up Swatch"                                ,
        "Grad Up Swatch Overlay"                        ,
        "grey_border"                                   ,
        "GridList"                                      ,
        "GridListText"                                  ,
        "GridToggle"                                    ,
        "GroupBox"                                      ,
        "GUIEditor.BreadcrumbLeft"                      ,
        "GUIEditor.BreadcrumbMid"                       ,
        "GV Gizmo DropDown"                             ,
        "HeaderLabel"                                   ,
        "HelpBox"                                       ,
        "Hi Label"                                      ,
        "HorizontalMinMaxScrollbarThumb"                ,
        "hostview"                                      ,
        "IN BigTitle"                                   ,
        "IN BigTitle Inner"                             ,
        "IN ColorField"                                 ,
        "IN DropDown"                                   ,
        "IN Foldout"                                    ,
        "IN FoldoutStatic"                              ,
        "IN Label"                                      ,
        "IN LockButton"                                 ,
        "IN ObjectField"                                ,
        "IN Popup"                                      ,
        "IN SelectedLine"                               ,
        "IN TextField"                                  ,
        "IN ThumbnailSelection"                         ,
        "IN ThumbnailShadow"                            ,
        "IN Title"                                      ,
        "IN TitleText"                                  ,
        "IN Toggle"                                     ,
        "InnerShadowBg"                                 ,
        "InvisibleButton"                               ,
        "LargeButton"                                   ,
        "LargeButtonLeft"                               ,
        "LargeButtonMid"                                ,
        "LargeButtonRight"                              ,
        "LargeDropDown"                                 ,
        "LargeLabel"                                    ,
        "LargePopup"                                    ,
        "LargeTextField"                                ,
        "LightmapEditorSelectedHighlight"               ,
        "ListToggle"                                    ,
        "LockedHeaderBackground"                        ,
        "LockedHeaderButton"                            ,
        "LockedHeaderLabel"                             ,
        "LODBlackBox"                                   ,
        "LODCameraLine"                                 ,
        "LODLevelNotifyText"                            ,
        "LODRendererAddButton"                          ,
        "LODRendererButton"                             ,
        "LODRendererRemove"                             ,
        "LODRenderersText"                              ,
        "LODSceneText"                                  ,
        "LODSliderBG"                                   ,
        "LODSliderRange"                                ,
        "LODSliderRangeSelected"                        ,
        "LODSliderText"                                 ,
        "LODSliderTextSelected"                         ,
        "MeBlendBackground"                             ,
        "MeBlendPosition"                               ,
        "MeBlendTriangleLeft"                           ,
        "MeBlendTriangleRight"                          ,
        "MeLivePlayBackground"                          ,
        "MeLivePlayBar"                                 ,
        "MeTimeLabel"                                   ,
        "MeTransBGOver"                                 ,
        "MeTransitionBack"                              ,
        "MeTransitionBlock"                             ,
        "MeTransitionHandleLeft"                        ,
        "MeTransitionHandleLeftPrev"                    ,
        "MeTransitionHandleRight"                       ,
        "MeTransitionHead"                              ,
        "MeTransitionSelect"                            ,
        "MeTransitionSelectHead"                        ,
        "MeTransOff2On"                                 ,
        "MeTransOffLeft"                                ,
        "MeTransOffRight"                               ,
        "MeTransOn2Off"                                 ,
        "MeTransOnLeft"                                 ,
        "MeTransOnRight"                                ,
        "MeTransPlayhead"                               ,
        "MiniBoldLabel"                                 ,
        "minibutton"                                    ,
        "minibuttonleft"                                ,
        "minibuttonmid"                                 ,
        "minibuttonright"                               ,
        "MiniLabel"                                     ,
        "MiniLabelRight"                                ,
        "MiniMinMaxSliderHorizontal"                    ,
        "MiniMinMaxSliderVertical"                      ,
        "MiniPopup"                                     ,
        "MiniPullDown"                                  ,
        "MiniPullDownLeft"                              ,
        "MiniTextField"                                 ,
        "MiniToolbarButton"                             ,
        "MiniToolbarButtonLeft"                         ,
        "MiniToolbarPopup"                              ,
        "MinMaxHorizontalSliderThumb"                   ,
        "NotificationBackground"                        ,
        "NotificationText"                              ,
        "ObjectField"                                   ,
        "ObjectFieldThumb"                              ,
        "ObjectFieldThumbOverlay"                       ,
        "ObjectFieldThumbOverlay2"                      ,
        "ObjectPickerBackground"                        ,
        "ObjectPickerGroupHeader"                       ,
        "ObjectPickerLargeStatus"                       ,
        "ObjectPickerPreviewBackground"                 ,
        "ObjectPickerResultsEven"                       ,
        "ObjectPickerResultsGrid"                       ,
        "ObjectPickerResultsGridLabel"                  ,
        "ObjectPickerResultsOdd"                        ,
        "ObjectPickerSmallStatus"                       ,
        "ObjectPickerTab"                               ,
        "ObjectPickerToolbar"                           ,
        "OL box"                                        ,
        "OL box NoExpand"                               ,
        "OL Elem"                                       ,
        "OL EntryBackEven"                              ,
        "OL EntryBackOdd"                               ,
        "OL header"                                     ,
        "OL Label"                                      ,
        "OL Minus"                                      ,
        "OL Plus"                                       ,
        "OL TextField"                                  ,
        "OL Title"                                      ,
        "OL Title TextRight"                            ,
        "OL Titleleft"                                  ,
        "OL Titlemid"                                   ,
        "OL Titleright"                                 ,
        "OL Toggle"                                     ,
        "OL ToggleWhite"                                ,
        "PaneOptions"                                   ,
        "PlayerSettingsLevel"                           ,
        "PlayerSettingsPlatform"                        ,
        "Popup"                                         ,
        "PopupBackground"                               ,
        "PopupCurveDropdown"                            ,
        "PopupCurveEditorBackground"                    ,
        "PopupCurveEditorSwatch"                        ,
        "PopupCurveSwatchBackground"                    ,
        "PR DigDownArrow"                               ,
        "PR Insertion"                                  ,
        "PR Label"                                      ,
        "PR Ping"                                       ,
        "PR TextField"                                  ,
        "PreBackground"                                 ,
        "PreButton"                                     ,
        "PreferencesKeysElement"                        ,
        "PreferencesSection"                            ,
        "PreferencesSectionBox"                         ,
        "PreHorizontalScrollbar"                        ,
        "PreHorizontalScrollbarThumb"                   ,
        "PreLabel"                                      ,
        "PreOverlayLabel"                               ,
        "PreSlider"                                     ,
        "PreSliderThumb"                                ,
        "PreToolbar"                                    ,
        "PreToolbar2"                                   ,
        "PreVerticalScrollbar"                          ,
        "PreVerticalScrollbarThumb"                     ,
        "ProfilerBadge"                                 ,
        "ProfilerLeftPane"                              ,
        "ProfilerLeftPaneOverlay"                       ,
        "ProfilerPaneLeftBackground"                    ,
        "ProfilerPaneSubLabel"                          ,
        "ProfilerRightPane"                             ,
        "ProfilerScrollviewBackground"                  ,
        "ProfilerSelectedLabel"                         ,
        "ProgressBarBack"                               ,
        "ProgressBarBar"                                ,
        "ProgressBarText"                               ,
        "ProjectBrowserBottomBarBg"                     ,
        "ProjectBrowserGridLabel"                       ,
        "ProjectBrowserHeaderBgMiddle"                  ,
        "ProjectBrowserHeaderBgTop"                     ,
        "ProjectBrowserIconAreaBg"                      ,
        "ProjectBrowserIconDropShadow"                  ,
        "ProjectBrowserPreviewBg"                       ,
        "ProjectBrowserSubAssetBg"                      ,
        "ProjectBrowserSubAssetBgCloseEnded"            ,
        "ProjectBrowserSubAssetBgDivider"               ,
        "ProjectBrowserSubAssetBgMiddle"                ,
        "ProjectBrowserSubAssetBgOpenEnded"             ,
        "ProjectBrowserSubAssetExpandBtn"               ,
        "ProjectBrowserTopBarBg"                        ,
        "QualitySettingsDefault"                        ,
        "Radio"                                         ,
        "RightLabel"                                    ,
        "RL Background"                                 ,
        "RL DragHandle"                                 ,
        "RL Element"                                    ,
        "RL Footer"                                     ,
        "RL FooterButton"                               ,
        "RL Header"                                     ,
        "SC ViewAxisLabel"                              ,
        "SC ViewLabel"                                  ,
        "SceneViewOverlayTransparentBackground"         ,
        "ScriptText"                                    ,
        "SearchCancelButton"                            ,
        "SearchCancelButtonEmpty"                       ,
        "SearchModeFilter"                              ,
        "SearchTextField"                               ,
        "SelectionRect"                                 ,
        "ServerChangeCount"                             ,
        "ServerUpdateChangeset"                         ,
        "ServerUpdateChangesetOn"                       ,
        "ServerUpdateInfo"                              ,
        "ServerUpdateLog"                               ,
        "ShurikenCheckMark"                             ,
        "ShurikenEffectBg"                              ,
        "ShurikenEmitterTitle"                          ,
        "ShurikenLabel"                                 ,
        "ShurikenLine"                                  ,
        "ShurikenMinus"                                 ,
        "ShurikenModuleBg"                              ,
        "ShurikenModuleTitle"                           ,
        "ShurikenObjectField"                           ,
        "ShurikenPlus"                                  ,
        "ShurikenPopUp"                                 ,
        "ShurikenToggle"                                ,
        "ShurikenValue"                                 ,
        "SimplePopup"                                   ,
        "SliderMixed"                                   ,
        "StaticDropdown"                                ,
        "sv_iconselector_back"                          ,
        "sv_iconselector_button"                        ,
        "sv_iconselector_labelselection"                ,
        "sv_iconselector_selection"                     ,
        "sv_iconselector_sep"                           ,
        "sv_label_0"                                    ,
        "sv_label_1"                                    ,
        "sv_label_2"                                    ,
        "sv_label_3"                                    ,
        "sv_label_4"                                    ,
        "sv_label_5"                                    ,
        "sv_label_6"                                    ,
        "sv_label_7"                                    ,
        "TabWindowBackground"                           ,
        "Tag MenuItem"                                  ,
        "Tag TextField"                                 ,
        "Tag TextField Button"                          ,
        "Tag TextField Empty"                           ,
        "TE NodeBackground"                             ,
        "TE NodeBox"                                    ,
        "TE NodeBoxSelected"                            ,
        "TE NodeLabelBot"                               ,
        "TE NodeLabelTop"                               ,
        "TE PinLabel"                                   ,
        "TE Toolbar"                                    ,
        "TE toolbarbutton"                              ,
        "TE ToolbarDropDown"                            ,
        "TimeScrubber"                                  ,
        "TimeScrubberButton"                            ,
        "TL BaseStateLogicBarOverlay"                   ,
        "TL EndPoint"                                   ,
        "TL InPoint"                                    ,
        "TL ItemTitle"                                  ,
        "TL LeftColumn"                                 ,
        "TL LeftItem"                                   ,
        "TL LogicBar 0"                                 ,
        "TL LogicBar 1"                                 ,
        "TL LogicBar parentgrey"                        ,
        "TL LoopSection"                                ,
        "TL OutPoint"                                   ,
        "TL Playhead"                                   ,
        "TL Range Overlay"                              ,
        "TL RightLine"                                  ,
        "TL Selection H1"                               ,
        "TL Selection H2"                               ,
        "TL SelectionBarCloseButton"                    ,
        "TL SelectionBarPreview"                        ,
        "TL SelectionBarText"                           ,
        "TL SelectionButton"                            ,
        "TL SelectionButton PreDropGlow"                ,
        "TL SelectionButtonName"                        ,
        "TL SelectionButtonNew"                         ,
        "TL tab left"                                   ,
        "TL tab mid"                                    ,
        "TL tab plus left"                              ,
        "TL tab plus right"                             ,
        "TL tab right"                                  ,
        "ToggleMixed"                                   ,
        "Toolbar"                                       ,
        "toolbarbutton"                                 ,
        "ToolbarDropDown"                               ,
        "ToolbarPopup"                                  ,
        "ToolbarSeachCancelButton"                      ,
        "ToolbarSeachCancelButtonEmpty"                 ,
        "ToolbarSeachTextField"                         ,
        "ToolbarSeachTextFieldPopup"                    ,
        "ToolbarSearchField"                            ,
        "ToolbarTextField"                              ,
        "Tooltip"                                       ,
        "U2D.createRect"                                ,
        "U2D.dragDot"                                   ,
        "U2D.dragDotDimmed"                             ,
        "VCS_StickyNote"                                ,
        "VCS_StickyNoteArrow"                           ,
        "VCS_StickyNoteLabel"                           ,
        "VCS_StickyNoteP4"                              ,
        "VerticalMinMaxScrollbarThumb"                  ,
        "VisibilityToggle"                              ,
        "WhiteBoldLabel"                                ,
        "WhiteLabel"                                    ,
        "WhiteLargeLabel"                               ,
        "WhiteMiniLabel"                                ,
        "WinBtnCloseActiveMac"                          ,
        "WinBtnCloseMac"                                ,
        "WinBtnCloseWin"                                ,
        "WinBtnInactiveMac"                             ,
        "WinBtnMaxActiveMac"                            ,
        "WinBtnMaxMac"                                  ,
        "WinBtnMaxWin"                                  ,
        "WinBtnMinActiveMac"                            ,
        "WinBtnMinMac"                                  ,
        "WinBtnMinWin"                                  ,
        "WindowBackground"                              ,
        "WindowBottomResize"                            ,
        "WindowResizeMac"                               ,
        "Wizard Box"                                    ,
        "Wizard Error"                                  ,
        "WordWrapLabel"                                 ,
        "WordWrappedLabel"                              ,
        "WordWrappedMiniLabel"                          ,
        "WrappedLabel"                                  ,
    };    
    #endregion
    private Vector2 mScrollPos;

    [MenuItem("EditrGUIReference/GUIReflence Window")]
    private static void editrGUIReference()
    {
        GetWindow<EditrGUIReference>(true);
    }

    private void OnGUI()
    {
        mScrollPos = EditorGUILayout.BeginScrollView(mScrollPos);
        foreach (var n in mList)
        {
            EditorGUILayout.BeginHorizontal(GUILayout.Height(48));
            {
                EditorGUILayout.SelectableLabel(n);
                EditorGUILayout.Toggle(false, n);
            }
            EditorGUILayout.EndHorizontal();
            GUILayout.Box(
                string.Empty,
                GUILayout.Width(position.width - 24),
                GUILayout.Height(1)
            );
        }
        EditorGUILayout.EndScrollView();
    }
}
#region Reference    
namespace EditorTools.GUIStyles
{
    public enum InspectorGUIStyle
    {
        AboutWIndowLicenseLabel,
        AC_LeftArrow,
        AC_RightArrow,
        AnimationCurveEditorBackground,
        AnimationEventBackground,
        AnimationEventTooltip,
        AnimationEventTooltipArrow,
        AnimationKeyframeBackground,
        AnimationRowEven,
        AnimationRowOdd,
        AnimationSelectionTextField,
        AnimationTimelineTick,
        AnimPropDropdown,
        AppToolbar,
        AS_TextArea,
        BoldLabel,
        BoldToggle,
        ButtonLeft,
        ButtonMid,
        ButtonRight,
        CN_Box,
        CN_CountBadge,
        CN_EntryBackEven,
        CN_EntryBackOdd,
        CN_EntryError,
        CN_EntryInfo,
        CN_EntryWarn,
        CN_Message,
        CN_StatusError,
        CN_StatusInfo,
        CN_StatusWarn,
        ColorField,
        ColorPicker2DThumb,
        ColorPickerBackground,
        ColorPickerBox,
        ColorPickerHorizThumb,
        ColorPickerVertThumb,
        Command,
        CommandLeft,
        CommandMid,
        CommandRight,
        ControlLabel,
        CurveEditorLabelTickmarks,
        debug_layout_box,
        dockarea,
        dockareaOverlay,
        dockareaStandalone,
        dragtab,
        dragtabbright,
        dragtabdropwindow,
        DropDown,
        DropDownButton,
        ErrorLabel,
        ExposablePopupItem,
        ExposablePopupMenu,
        EyeDropperHorizontalLine,
        EyeDropperPickedPixel,
        EyeDropperVerticalLine,
        flow_background,
        flow_navbar_back,
        flow_navbar_button,
        flow_navbar_separator,
        flow_node_0,
        flow_node_0_on,
        flow_node_1,
        flow_node_1_on,
        flow_node_2,
        flow_node_2_on,
        flow_node_3,
        flow_node_3_on,
        flow_node_4,
        flow_node_4_on,
        flow_node_5,
        flow_node_5_on,
        flow_node_6,
        flow_node_6_on,
        flow_node_hex_0,
        flow_node_hex_0_on,
        flow_node_hex_1,
        flow_node_hex_1_on,
        flow_node_hex_2,
        flow_node_hex_2_on,
        flow_node_hex_3,
        flow_node_hex_3_on,
        flow_node_hex_4,
        flow_node_hex_4_on,
        flow_node_hex_5,
        flow_node_hex_5_on,
        flow_node_hex_6,
        flow_node_hex_6_on,
        flow_node_titlebar,
        flow_overlay_area_left,
        flow_overlay_area_right,
        flow_overlay_box,
        flow_overlay_foldout,
        flow_overlay_header_lower_left,
        flow_overlay_header_lower_right,
        flow_overlay_header_upper_left,
        flow_overlay_header_upper_right,
        flow_shader_in_0,
        flow_shader_in_1,
        flow_shader_in_2,
        flow_shader_in_3,
        flow_shader_in_4,
        flow_shader_in_5,
        flow_shader_node_0,
        flow_shader_node_0_on,
        flow_shader_out_0,
        flow_shader_out_1,
        flow_shader_out_2,
        flow_shader_out_3,
        flow_shader_out_4,
        flow_shader_out_5,
        flow_target_IN_,
        flow_triggerPin_IN_,
        flow_triggerPin_out,
        flow_var_0,
        flow_var_0_on,
        flow_var_1,
        flow_var_1_on,
        flow_var_2,
        flow_var_2_on,
        flow_var_3,
        flow_var_3_on,
        flow_var_4,
        flow_var_4_on,
        flow_var_5,
        flow_var_5_on,
        flow_var_6,
        flow_var_6_on,
        flow_varPin_IN_,
        flow_varPin_out,
        flow_varPin_tooltip,
        Foldout,
        FoldOutPreDrop,
        GameViewBackground,
        Grad_Down_Swatch,
        Grad_Down_Swatch_Overlay,
        Grad_Up_Swatch,
        Grad_Up_Swatch_Overlay,
        grey_border,
        GridList,
        GridListText,
        GridToggle,
        GroupBox,
        GUIEditorDOTBreadcrumbLeft,
        GUIEditorDOTBreadcrumbMid,
        GV_Gizmo_DropDown,
        HeaderLabel,
        HelpBox,
        Hi_Label,
        HorizontalMinMaxScrollbarThumb,
        hostview,
        IN_BigTitle,
        IN_BigTitle_Inner,
        IN_ColorField,
        IN_DropDown,
        IN_Foldout,
        IN_FoldoutStatic,
        IN_Label,
        IN_LockButton,
        IN_ObjectField,
        IN_Popup,
        IN_SelectedLine,
        IN_TextField,
        IN_ThumbnailSelection,
        IN_ThumbnailShadow,
        IN_Title,
        IN_TitleText,
        IN_Toggle,
        InnerShadowBg,
        InvisibleButton,
        LargeButton,
        LargeButtonLeft,
        LargeButtonMid,
        LargeButtonRight,
        LargeDropDown,
        LargeLabel,
        LargePopup,
        LargeTextField,
        LightmapEditorSelectedHighlight,
        ListToggle,
        LockedHeaderBackground,
        LockedHeaderButton,
        LockedHeaderLabel,
        LODBlackBox,
        LODCameraLine,
        LODLevelNotifyText,
        LODRendererAddButton,
        LODRendererButton,
        LODRendererRemove,
        LODRenderersText,
        LODSceneText,
        LODSliderBG,
        LODSliderRange,
        LODSliderRangeSelected,
        LODSliderText,
        LODSliderTextSelected,
        MeBlendBackground,
        MeBlendPosition,
        MeBlendTriangleLeft,
        MeBlendTriangleRight,
        MeLivePlayBackground,
        MeLivePlayBar,
        MeTimeLabel,
        MeTransBGOver,
        MeTransitionBack,
        MeTransitionBlock,
        MeTransitionHandleLeft,
        MeTransitionHandleLeftPrev,
        MeTransitionHandleRight,
        MeTransitionHead,
        MeTransitionSelect,
        MeTransitionSelectHead,
        MeTransOff2On,
        MeTransOffLeft,
        MeTransOffRight,
        MeTransOn2Off,
        MeTransOnLeft,
        MeTransOnRight,
        MeTransPlayhead,
        MiniBoldLabel,
        minibutton,
        minibuttonleft,
        minibuttonmid,
        minibuttonright,
        MiniLabel,
        MiniLabelRight,
        MiniMinMaxSliderHorizontal,
        MiniMinMaxSliderVertical,
        MiniPopup,
        MiniPullDown,
        MiniPullDownLeft,
        MiniTextField,
        MiniToolbarButton,
        MiniToolbarButtonLeft,
        MiniToolbarPopup,
        MinMaxHorizontalSliderThumb,
        NotificationBackground,
        NotificationText,
        ObjectField,
        ObjectFieldThumb,
        ObjectFieldThumbOverlay,
        ObjectFieldThumbOverlay2,
        ObjectPickerBackground,
        ObjectPickerGroupHeader,
        ObjectPickerLargeStatus,
        ObjectPickerPreviewBackground,
        ObjectPickerResultsEven,
        ObjectPickerResultsGrid,
        ObjectPickerResultsGridLabel,
        ObjectPickerResultsOdd,
        ObjectPickerSmallStatus,
        ObjectPickerTab,
        ObjectPickerToolbar,
        OL_box,
        OL_box_NoExpand,
        OL_Elem,
        OL_EntryBackEven,
        OL_EntryBackOdd,
        OL_header,
        OL_Label,
        OL_Minus,
        OL_Plus,
        OL_TextField,
        OL_Title,
        OL_Title_TextRight,
        OL_Titleleft,
        OL_Titlemid,
        OL_Titleright,
        OL_Toggle,
        OL_ToggleWhite,
        PaneOptions,
        PlayerSettingsLevel,
        PlayerSettingsPlatform,
        Popup,
        PopupBackground,
        PopupCurveDropdown,
        PopupCurveEditorBackground,
        PopupCurveEditorSwatch,
        PopupCurveSwatchBackground,
        PR_DigDownArrow,
        PR_insertion,
        PR_Label,
        PR_Ping,
        PR_TextField,
        PreBackground,
        PreButton,
        PreferencesKeysElement,
        PreferencesSection,
        PreferencesSectionBox,
        PreHorizontalScrollbar,
        PreHorizontalScrollbarThumb,
        PreLabel,
        PreOverlayLabel,
        PreSlider,
        PreSliderThumb,
        PreToolbar,
        PreToolbar2,
        PreVerticalScrollbar,
        PreVerticalScrollbarThumb,
        ProfilerBadge,
        ProfilerLeftPane,
        ProfilerLeftPaneOverlay,
        ProfilerPaneLeftBackground,
        ProfilerPaneSubLabel,
        ProfilerRightPane,
        ProfilerScrollviewBackground,
        ProfilerSelectedLabel,
        ProgressBarBack,
        ProgressBarBar,
        ProgressBarText,
        ProjectBrowserBottomBarBg,
        ProjectBrowserGridLabel,
        ProjectBrowserHeaderBgMiddle,
        ProjectBrowserHeaderBgTop,
        ProjectBrowserIconAreaBg,
        ProjectBrowserIconDropShadow,
        ProjectBrowserPreviewBg,
        ProjectBrowserSubAssetBg,
        ProjectBrowserSubAssetBgCloseEnded,
        ProjectBrowserSubAssetBgDivider,
        ProjectBrowserSubAssetBgMiddle,
        ProjectBrowserSubAssetBgOpenEnded,
        ProjectBrowserSubAssetExpandBtn,
        ProjectBrowserTopBarBg,
        QualitySettingsDefault,
        Radio,
        RightLabel,
        RL_Background,
        RL_DragHandle,
        RL_Element,
        RL_Footer,
        RL_FooterButton,
        RL_Header,
        SC_ViewAxisLabel,
        SC_ViewLabel,
        SceneViewOverlayTransparentBackground,
        ScriptText,
        SearchCancelButton,
        SearchCancelButtonEmpty,
        SearchModeFilter,
        SearchTextField,
        SelectionRect,
        ServerChangeCount,
        ServerUpdateChangeset,
        ServerUpdateChangesetOn,
        ServerUpdateInfo,
        ServerUpdateLog,
        ShurikenCheckMark,
        ShurikenEffectBg,
        ShurikenEmitterTitle,
        ShurikenLabel,
        ShurikenLine,
        ShurikenMinus,
        ShurikenModuleBg,
        ShurikenModuleTitle,
        ShurikenObjectField,
        ShurikenPlus,
        ShurikenPopUp,
        ShurikenToggle,
        ShurikenValue,
        SimplePopup,
        SliderMixed,
        StaticDropdown,
        sv_iconselector_back,
        sv_iconselector_button,
        sv_iconselector_labelselection,
        sv_iconselector_selection,
        sv_iconselector_sep,
        sv_label_0,
        sv_label_1,
        sv_label_2,
        sv_label_3,
        sv_label_4,
        sv_label_5,
        sv_label_6,
        sv_label_7,
        TabWindowBackground,
        Tag_MenuItem,
        Tag_TextField,
        Tag_TextField_Button,
        Tag_TextField_Empty,
        TE_NodeBackground,
        TE_NodeBox,
        TE_NodeBoxSelected,
        TE_NodeLabelBot,
        TE_NodeLabelTop,
        TE_PinLabel,
        TE_Toolbar,
        TE_toolbarbutton,
        TE_ToolbarDropDown,
        TimeScrubber,
        TimeScrubberButton,
        TL_BaseStateLogicBarOverlay,
        TL_EndPoint,
        TL_InPoint,
        TL_ItemTitle,
        TL_LeftColumn,
        TL_LeftItem,
        TL_LogicBar_0,
        TL_LogicBar_1,
        TL_LogicBar_parentgrey,
        TL_LoopSection,
        TL_OutPoint,
        TL_Playhead,
        TL_Range_Overlay,
        TL_RightLine,
        TL_Selection_H1,
        TL_Selection_H2,
        TL_SelectionBarCloseButton,
        TL_SelectionBarPreview,
        TL_SelectionBarText,
        TL_SelectionButton,
        TL_SelectionButton_PreDropGlow,
        TL_SelectionButtonName,
        TL_SelectionButtonNew,
        TL_tab_left,
        TL_tab_mid,
        TL_tab_plus_left,
        TL_tab_plus_right,
        TL_tab_right,
        ToggleMixed,
        Toolbar,
        toolbarbutton,
        ToolbarDropDown,
        ToolbarPopup,
        ToolbarSeachCancelButton,
        ToolbarSeachCancelButtonEmpty,
        ToolbarSeachTextField,
        ToolbarSeachTextFieldPopup,
        ToolbarSearchField,
        ToolbarTextField,
        Tooltip,
        U2DDOTcreateRect,
        U2DDOTdragDot,
        U2DDOTdragDotDimmed,
        VCS_StickyNote,
        VCS_StickyNoteArrow,
        VCS_StickyNoteLabel,
        VCS_StickyNoteP4,
        VerticalMinMaxScrollbarThumb,
        VisibilityToggle,
        WhiteBoldLabel,
        WhiteLabel,
        WhiteLargeLabel,
        WhiteMiniLabel,
        WinBtnCloseActiveMac,
        WinBtnCloseMac,
        WinBtnCloseWIN_,
        WinBtnInactiveMac,
        WinBtnMaxActiveMac,
        WinBtnMaxMac,
        WinBtnMaxWIN_,
        WinBtnMinActiveMac,
        WinBtnMinMac,
        WinBtnMinWIN_,
        WindowBackground,
        WindowBottomResize,
        WindowResizeMac,
        Wizard_Box,
        Wizard_Error,
        WordWrapLabel,
        WordWrappedLabel,
        WordWrappedMiniLabel,
        WrappedLabel,

    }

}
#endregion